### ISSUE TITLE
https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json doesn't exist

### ISSUE THREAD

**Issue by kazu0622** [microsoft/ailab#130]
I tried to build Speaker.Recorder in VS2019 ,but I 'm facing the issue that https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json doesn't exist.
I'd like to know how to cope with this issue.

Thanks.

**Comment by ttkrpink** [comment]
Same problem, anyone can help?

**Comment by ttkrpink** [comment]
Hi, Kazu,
How did you solve the problem with index.json doesn't exist?


Thansk


ttk






发件人：kazu0622 ***@***.***>
发送日期：2021-11-26 14:58:10
收件人：microsoft/ailab ***@***.***>
抄送人：ttkrpink ***@***.***>,Comment ***@***.***>
主题：Re: [microsoft/ailab] https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json doesn't exist (#130)

Closed #130.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kazu0622** [comment]
@ttkrpink Unfortunately, I wasn't able to find a solution.

**Comment by luuk777w** [comment]
For anyone who is facing this problem:

You need to remove `https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json` from `Directory.Build.props`

Then in `Speaker.Recorder.csproj` you need to change this:

```
    <PackageReference Include="Microsoft.Toolkit.Win32.UI.SDK" Version="6.1.0-build.1" />
    <PackageReference Include="Microsoft.Toolkit.Wpf.UI.Controls" Version="6.1.0-build.1" />
```

to this:

```
    <PackageReference Include="Microsoft.Toolkit.Win32.UI.SDK" Version="6.1.0" />
    <PackageReference Include="Microsoft.Toolkit.Wpf.UI.Controls" Version="6.1.0" />
```

As well as in `Speaker.Recorder.UWP.csproj` change this:

```
    <PackageReference Include="Microsoft.Toolkit.Win32.UI.XamlApplication">
      <Version>6.1.0-build.1</Version>
    </PackageReference>
```

to this: 

```
    <PackageReference Include="Microsoft.Toolkit.Win32.UI.XamlApplication">
      <Version>6.1.0</Version>
    </PackageReference>
```
