### ISSUE TITLE
Doesn't recognize simple user form

### ISSUE THREAD

**Issue by srivatsahg** [Microsoft/ailab#4]
![sample](https://user-images.githubusercontent.com/2742470/44970824-f8ca3700-af70-11e8-9391-c30ffb3c08f7.png)

Not able to recognize the attached image to HTML. 
Output is blank HTML

**Comment by aniruddhapatil** [comment]
I tried a simple user registration form(Register Sample.jpg) and result was not too good. Textboxes, Labels and Text were not recognized 
![register sample](https://user-images.githubusercontent.com/24712378/45014762-47dd9e00-b03d-11e8-8c7c-bcd99726e328.jpg)
![result](https://user-images.githubusercontent.com/24712378/45014764-47dd9e00-b03d-11e8-94db-471683406763.JPG)

**Comment by tarasha** [comment]
We are dealing with multiple projects in the backend, due to a quota exhaustion issues we are facing with custom vision prediction, and hence when the application is connected to a less iteration based project; it may have some issues; like here. We are working had to ensure all our products have good number of iterations; as compared to the original project to ensure better results. Though, please note that this is an experiment and sample app; and we are looking forward to your inputs and additions to this open source project to take it to the next level. Please keep writing to us here!
