### ISSUE TITLE
Responsive problem 

### ISSUE THREAD

**Issue by ahmedalmulki** [Microsoft/ailab#5]
I think you should improve the mobile version because in PC almost everything is good but not in mobile devices, there are many bad sections in small devices.

**Comment by macastejon** [comment]
What is the mobile device you are using? We have tested some standard configurations but may not worked perfectly on every device. Can you provide some screenshots?

**Comment by ahmedalmulki** [comment]
Actually, I am using google DevTools then toggle device toolbar and from there I tried some devices like Galaxy S5, [Like here](http://nimb.ws/dOH8P2), I think the sections should be one after one in small devices.
but anyway it's a good start and I love it.

**Comment by macastejon** [comment]
I see the problem. One thing to think about. The problem here maybe related with the size of the font we have used by default, but it also has to do with a bigger challenge that is relating different elements together (like the image and the paragraph) so you can code the final HTML keeping them together. Really interesting feature, thanks

**Comment by tarasha** [comment]
Thanks @macastejon, closing the issue for now
